name: tsa
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - ipykernel
  - jupyter
  - ipython
  - nb_conda_kernels
  - pip
  - pip:
    - plotly
    - sklearn
    - xlrd
